# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: TFS PO Tool API
  description: Kommt später
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /tfspotool-1.0-SNAPSHOT/v1/
produces:
  - application/json
paths:
  /goals:
    get:
      summary: Get all goals.
      tags:
        - Goals
      responses:
        200:
          description: An array of goal-IDs
          schema:
            type: array
            items:
              $ref: '#/definitions/GoalId'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /goals/{goalId}:
    get:
      summary: Get a goal by ID
      parameters:
        - in: path
          name: goalId
          required: true
          type: integer
          description: numeric Id of the goal
      responses:
        200:
          description: The goal with the ID
          schema:
            $ref: '#/definitions/Goal'
definitions:
  GoalId:
    type: integer
  Error:
    type: string
  Goal:
    type: object
    properties:
      details:
        type: string
        description: the detailfield of a goal
      goalDescription:
        type: string
        description: the goal description
